"""
Profanity and stop-words database for AOSP dictionaries.

Keys: lowercase language code (e.g. 'de_ch', 'pt_br').
PROFANITY_DB[lang]  = words to flag as possibly_offensive=true
STOP_WORDS_DB[lang] = false-positive overrides — matched words have the flag removed
"""

# fmt: off

PROFANITY_DB: dict[str, set[str]] = {
    "de_ch": {
        "abgespritzt", "abspritzen", "affesiech", "analritter", "analritters", "anus", "arsch", "arsches",
        "arschficker", "arschfickers", "arschgeige", "arschgeigen", "arschkriecher", "arschkriechers", "arschlecker", "arschleckers",
        "arschloch", "arschlochs", "arschlöcher", "arschlöchern", "arschtritt", "arschtritte", "bastard", "bastarde",
        "beschissen", "beschissene", "beschissenen", "beschissener", "beschissenes", "bimbo", "bitch", "bitches",
        "blöödsiech", "bratze", "brunzen", "brunzt", "bumsen", "bumst", "bumste", "bückstück",
        "bückstücke", "bückstücks", "cheibesiech", "cheibssiech", "drecksau", "dreckshure", "drecksloch", "dreckslöcher",
        "drecksstück", "dreckwichser", "dräcksiech", "dräckssiech", "dummsiech", "fick", "ficken", "ficker",
        "fickers", "fickfehler", "fickgesicht", "fickschlitten", "fickst", "fickt", "fickte", "fickten",
        "flachwixer", "flittchen", "fotze", "fotzen", "fotzenknecht", "fotzenknechte", "fotzenknechts", "fotzloch",
        "futz", "futze", "fötzeli", "füdloch", "gebumst", "gefickt", "gefickte", "gefickten",
        "gefickter", "geficktes", "gekackt", "gepimpert", "gepisst", "gepoppt", "geschnackelt", "gevögelt",
        "gewichst", "gopfertami", "grüsel", "gummihals", "hackfresse", "halbschueh", "huere", "huerenaffe",
        "huerenaffen", "hueresiech", "hundesohn", "hundsverlochete", "hure", "huren", "hurenbock", "hurensohn",
        "hurensöhne", "hustensohn", "jugo", "jugos", "kackbratze", "kacke", "kacken", "kackt",
        "kackvogel", "kackwurst", "kackwürste", "kampflesbe", "kampflesben", "kanake", "kanaken", "klitoris",
        "klugscheisser", "lumpeseggel", "milf", "milfs", "missgeburt", "missgeburten", "morgenlatte", "morgenlatten",
        "motherfucker", "muschi", "möse", "mösen", "neger", "nigger", "nutte", "nutten",
        "nuttensohn", "onanieren", "onaniert", "onanierte", "pajass", "penis", "pimmel", "pimmelkopf",
        "pimmelkopfs", "pimmelköpfe", "pimmels", "pimpern", "pimpert", "pisse", "pissen", "pisser",
        "pissers", "pissgesicht", "pisskopf", "pissnelke", "pisst", "pisste", "poppen", "poppt",
        "poppte", "rosettenhengst", "rosettenhengste", "rosettenhengsts", "sackgrind", "sackloch", "saftarsch", "saftsack",
        "sauhund", "sauschwob", "sauschwobe", "sausiech", "schaafseckel", "schabracke", "scheissdreck", "scheisse",
        "scheisser", "scheisskerl", "scheisskopf", "schiesser", "schlampe", "schlampen", "schluucht", "schlüecht",
        "schnackeln", "schnackelt", "schnäbichätscher", "schofseckel", "schwanzkopf", "schwanzkopfs", "schwanzköpfe", "schwanzlutscher",
        "schweinehund", "schwuchtel", "schwuchteln", "schyssdreck", "schyssdräck", "schysse", "schysser", "schysssiech",
        "seich", "seiche", "seichi", "siechgrind", "spast", "spasten", "spasti", "sperma",
        "spermafresse", "spermafressen", "säuniggel", "tittchen", "titten", "tschingg", "tschingge", "tscholi",
        "vagina", "verarsche", "verarschen", "verarscht", "verfickt", "verfickte", "verfickten", "verfickter",
        "verficktes", "verpissen", "verpisst", "vollpfosten", "vulva", "vögeln", "wicher", "wichsbueb",
        "wichsbüebli", "wichse", "wichsen", "wichser", "wichsgesicht", "wichst", "wichste", "wixgesicht",
        "wixxer", "ärsche", "ärschen",
    },

    "pt_br": {
        "anus", "arrombada", "arrombadas", "arrombado", "arrombados", "baba-ovo", "babaca", "babacas",
        "babaovo", "bagos", "baitola", "baitolas", "balalao", "bastardo", "bebum", "biscate",
        "biscates", "bixa", "boazuda", "boceta", "boco", "bocó", "boiola", "bolagato",
        "boob", "boquete", "boqueteira", "boqueteiras", "boqueteiro", "bosseta", "bosta", "bostas",
        "bosteiro", "bostinha", "bostolhão", "brioco", "bronha", "buceta", "bucetas", "bucetuda",
        "bugre", "bunda", "bunduda", "bundão", "bussanga", "busseta", "cabrao", "caceta",
        "cacete", "cadela", "caga", "cagado", "cagar", "cagona", "cagão", "canalha",
        "caralhento", "caralho", "caralhos", "caraçhaço", "casseta", "cassete", "checheca", "chereca",
        "chifruda", "chifrudo", "chochonho", "chochota", "chota", "chupa-pinto", "chupa-rola", "chupa-saco",
        "chupar", "clitoris", "clitóris", "cona", "corna", "corno", "cornos", "cu",
        "cuzona", "cuzão", "cuzões", "cú", "escrota", "escrotice", "escrotices", "escroto",
        "escrotos", "esporra", "esporro", "fanchona", "fdp", "fiofó", "foda", "foda-se",
        "fodas", "fode", "fodedor", "fodedora", "foder", "fodida", "fodido", "fodona",
        "fodão", "fudendo", "fuder", "fudida", "fudido", "fuleira", "jossa", "kenga",
        "machona", "merda", "merdas", "merdelhão", "mizera", "mocrea", "mocreia", "pau-no-cu",
        "pentelha", "pentelho", "pepeka", "perereca", "piriguete", "piriguetes", "piroca", "pirocudo",
        "piru", "pnc", "porra", "pqp", "punheta", "punheteiro", "punheteiros", "puta",
        "putaria", "putas", "puto", "putona", "putonas", "putos", "puxa-saco", "puxasaco",
        "pênis", "quenga", "quengas", "rapariga", "raparigas", "recalcada", "recalcado", "retardada",
        "retardado", "rolinha", "roludo", "rosca", "sacanagem", "sapatona", "sapatão", "siririca",
        "siririqueira", "siririqueiras", "tarada", "tarado", "tesão", "tezuda", "tezudo", "tezão",
        "tiriça", "transar", "vadia", "vadias", "vagaranha", "vagina", "veada", "veadão",
        "viada", "viadinho", "viado", "viadão", "vtnc", "vulva", "víado", "xana",
        "xavasca", "xavascuda", "xereca", "xerereca", "xexeca", "xochota", "xota", "xoxota",
        "xoxotuda", "ânus",
    },

    "sr": {
        "анус", "балија", "балије", "вагина", "вукојебина", "вулва", "говна", "говнар",
        "говнари", "говнарија", "говнив", "говнима", "говно", "говном", "говну", "гузица",
        "гузицама", "гузице", "гузицетина", "гузици", "гузицом", "гузицу", "дојебао", "дојебати",
        "дојебем", "дркала", "дркали", "дркам", "дркамо", "дркао", "дркате", "дркати",
        "дркач", "дркаш", "дркају", "дркање", "дркаџија", "дркош", "зајебала", "зајебан",
        "зајебана", "зајебани", "зајебано", "зајебанција", "зајебао", "зајебати", "зајебе", "зајебем",
        "зајебеш", "зајеби", "зајебите", "изјебала", "изјебан", "изјебана", "изјебао", "изјебати",
        "кара", "карала", "карам", "карамо", "карао", "карате", "карати", "караш",
        "карају", "карање", "клиторис", "курац", "курва", "курвама", "курварство", "курве",
        "курви", "курвин", "курву", "курца", "курцем", "курци", "курцима", "курцобоља",
        "курцу", "курчева", "курчеви", "курчеву", "курчина", "курчине", "курчић", "мрш",
        "најебала", "најебан", "најебана", "најебао", "најебати", "најебе", "најебем", "најебеш",
        "одјебала", "одјебао", "одјебати", "одјебе", "одјебем", "одјебеш", "одјеби", "одјебите",
        "ојебала", "ојебан", "ојебана", "ојебао", "ојебати", "педер", "педераст", "педери",
        "педерима", "педеру", "педерчина", "педерчине", "педерчуга", "пенис", "пизда", "пиздама",
        "пиздарија", "пиздарије", "пизде", "пизди", "пиздом", "пизду", "пиздун", "пиздуни",
        "пицка", "пицке", "пичка", "пичкама", "пичке", "пичкетина", "пичкетине", "пички",
        "пичкин", "пичкица", "пичкице", "пичком", "пичку", "попиздео", "попиздети", "попиздим",
        "попиздиш", "посрао", "посрати", "појебала", "појебан", "појебана", "појебао", "појебати",
        "прдела", "прдем", "прдео", "прдети", "прди", "прднути", "прејебао", "прејебати",
        "прејебем", "просерем", "просрати", "пројебала", "пројебан", "пројебана", "пројебао", "пројебати",
        "разјебала", "разјебани", "разјебано", "разјебао", "разјебати", "разјебем", "раскарати", "сератор",
        "сератори", "срала", "срали", "срао", "срати", "срања", "срање", "срању",
        "сјебала", "сјебана", "сјебани", "сјебано", "сјебао", "сјебати", "сјебе", "сјебем",
        "сјебемо", "сјебете", "сјебеш", "сјебу", "усерем", "усрала", "усрани", "усрао",
        "усрати", "ујебала", "ујебано", "ујебао", "ујебати", "ујебем", "фуфа", "фуфе",
        "циган", "цигани", "циганин", "циганка", "црнчуга", "шиптар", "шиптари", "шиптарка",
        "шиптарке", "шупак", "шупка", "шупком", "шупку", "шупци", "шупцима", "шупчина",
        "јебала", "јебали", "јебао", "јебати", "јебач", "јебачи", "јебачина", "јебачине",
        "јебања", "јебање", "јебе", "јебем", "јебемо", "јебете", "јебеш", "јеби",
        "јебите", "јебу",
    },

    "sr_zz": {
        "anus", "balija", "balije", "cigan", "cigani", "ciganin", "ciganka", "crnčuga",
        "dojebao", "dojebati", "dojebem", "drkadžija", "drkaju", "drkala", "drkali", "drkam",
        "drkamo", "drkanje", "drkao", "drkate", "drkati", "drkač", "drkaš", "drkoš",
        "fufa", "fufe", "govna", "govnar", "govnari", "govnarija", "govnima", "govniv",
        "govno", "govnom", "govnu", "guzica", "guzicama", "guzice", "guzicetina", "guzici",
        "guzicom", "guzicu", "izjebala", "izjeban", "izjebana", "izjebao", "izjebati", "jebala",
        "jebali", "jebanja", "jebanje", "jebao", "jebati", "jebač", "jebači", "jebačina",
        "jebačine", "jebe", "jebem", "jebemo", "jebete", "jebeš", "jebi", "jebite",
        "jebu", "kara", "karaju", "karala", "karam", "karamo", "karanje", "karao",
        "karate", "karati", "karaš", "klitoris", "kurac", "kurca", "kurcem", "kurci",
        "kurcima", "kurcobolja", "kurcu", "kurva", "kurvama", "kurvarstvo", "kurve", "kurvi",
        "kurvin", "kurvu", "kurčeva", "kurčevi", "kurčevu", "kurčina", "kurčine", "kurčić",
        "mrš", "najebala", "najeban", "najebana", "najebao", "najebati", "najebe", "najebem",
        "najebeš", "odjebala", "odjebao", "odjebati", "odjebe", "odjebem", "odjebeš", "odjebi",
        "odjebite", "ojebala", "ojeban", "ojebana", "ojebao", "ojebati", "peder", "pederast",
        "pederi", "pederima", "pederu", "pederčina", "pederčine", "pederčuga", "penis", "picka",
        "picke", "pizda", "pizdama", "pizdarija", "pizdarije", "pizde", "pizdi", "pizdom",
        "pizdu", "pizdun", "pizduni", "pička", "pičkama", "pičke", "pičketina", "pičketine",
        "pički", "pičkica", "pičkice", "pičkin", "pičkom", "pičku", "pojebala", "pojeban",
        "pojebana", "pojebao", "pojebati", "popizdeo", "popizdeti", "popizdim", "popizdiš", "posrao",
        "posrati", "prdela", "prdem", "prdeo", "prdeti", "prdi", "prdnuti", "prejebao",
        "prejebati", "prejebem", "projebala", "projeban", "projebana", "projebao", "projebati", "proserem",
        "prosrati", "raskarati", "razjebala", "razjebani", "razjebano", "razjebao", "razjebati", "razjebem",
        "serator", "seratori", "sjebala", "sjebana", "sjebani", "sjebano", "sjebao", "sjebati",
        "sjebe", "sjebem", "sjebemo", "sjebete", "sjebeš", "sjebu", "srala", "srali",
        "sranja", "sranje", "sranju", "srao", "srati", "ujebala", "ujebano", "ujebao",
        "ujebati", "ujebem", "userem", "usrala", "usrani", "usrao", "usrati", "vagina",
        "vukojebina", "vulva", "zajebala", "zajeban", "zajebana", "zajebancija", "zajebani", "zajebano",
        "zajebao", "zajebati", "zajebe", "zajebem", "zajebeš", "zajebi", "zajebite", "šiptar",
        "šiptari", "šiptarka", "šiptarke", "šupak", "šupci", "šupcima", "šupka", "šupkom",
        "šupku", "šupčina",
    },

}

STOP_WORDS_DB: dict[str, set[str]] = {
    "de_ch": {
        "bisexuell", "bisexuelle", "blöd", "blöde", "bock", "brust", "brüste", "böcke",
        "depp", "deppen", "doof", "doofe", "dumm", "dumme", "esel", "gott",
        "gottes", "homo", "homos", "homosexuell", "homosexuelle", "hund", "hunde", "hölle",
        "höllen", "idiot", "idioten", "kondom", "kondome", "kuh", "körper", "körpers",
        "kühe", "lesbisch", "lesbische", "mist", "miste", "nackt", "nackte", "nummer",
        "nummern", "porno", "pornografie", "prostituierte", "prostituierten", "scheisse", "schwein", "schweine",
        "schwul", "schwule", "sexuell", "sexuelle", "stute", "stuten", "teufel", "teufels",
        "trottel", "trottels", "tüpfel", "verdammt", "verdammte", "vogel", "volldepp", "volldeppen",
        "vollidiot", "vollidioten", "vögel", "ziege", "ziegen",
    },

    "pt_br": {
        "aborto", "amador", "aranha", "besta", "bicha", "bichas", "bissexual", "bobo",
        "bobão", "bode", "bodes", "bumbum", "burra", "burro", "burros", "cabra",
        "cabras", "cachorra", "cachorro", "camisinha", "cana", "canas", "cerveja", "cocaína",
        "coco", "cocos", "comer", "consolo", "corpo", "corpos", "cretina", "cretino",
        "desgraça", "desgraçada", "desgraçado", "diabo", "diabos", "estúpida", "estúpidas", "estúpido",
        "estúpidos", "fecal", "frango", "furo", "furos", "gajo", "gajos", "galinha",
        "gay", "gays", "gozar", "grelho", "grelinho", "grelo", "heroína", "heterosexual",
        "homoerótico", "homosexual", "homossexuais", "homossexual", "idiota", "idiotas", "idiotice", "imbecil",
        "imbecis", "inferno", "infernos", "lésbica", "macaca", "macaco", "mama", "mané",
        "mijada", "mijado", "mijo", "nu", "nua", "nuas", "nus", "otária",
        "otário", "parva", "parvas", "parvo", "parvos", "pateta", "patetas", "pau",
        "peidar", "peido", "peito", "peitos", "peru", "pica", "picas", "pinto",
        "pintos", "pipi", "pipis", "piranha", "porca", "porcas", "porno", "pornografia",
        "preservativo", "preservativos", "prostituta", "prostitutas", "rabo", "rabuda", "rabudo", "rabudona",
        "rabudão", "rabão", "rola", "rolas", "saco", "safada", "safado", "seios",
        "sexuais", "sexual", "toba", "toco", "tocos", "tola", "tolas", "tolo",
        "tolos", "torneira", "trocha", "troucha", "trouxa", "troxa", "vaca", "vacas",
        "vagabunda", "vagabundo", "veado", "veados", "vibrador",
    },

    "sr": {
        "biseksualac", "biseksualci", "bog", "boga", "bože", "budala", "budale", "dojke",
        "dupe", "dupeta", "gej", "gejevi", "glupaci", "glupan", "go", "gola",
        "goli", "golo", "grudi", "homoseksualac", "homoseksualci", "idiot", "idioti", "jaram",
        "jare", "kondom", "kondomi", "konj", "konja", "konji", "koza", "koze",
        "krava", "krave", "kreten", "kreteni", "lezbejka", "lezbejke", "magarac", "magarca",
        "magare", "maloumnici", "maloumnik", "mangup", "mangupa", "pakao", "pakla", "pas",
        "porno", "pornografija", "prostitutka", "prostitutke", "psa", "psi", "psima", "seksualan",
        "seksualni", "sisa", "sise", "sranje", "svinja", "svinje", "tela", "telo",
        "đavo", "đavola", "đavoli",
    },

    "sr_zz": set(),

}

# fmt: on
